/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dirrtyharry.music.collection.tracker;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
  @Test
  public void testAppHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull("app should have a greeting", classUnderTest.toString());
  }
}
