/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dirrtyharry.music.collection.tracker;

import java.io.File;
import java.util.List;

import com.dirrtyharry.music.collection.tracker.comparator.ByAlbumCount;
import com.dirrtyharry.music.collection.tracker.model.Artist;
import com.dirrtyharry.music.collection.tracker.reader.FolderReader;
import com.dirrtyharry.music.collection.tracker.writer.CsvWriter;
import com.dirrtyharry.music.collection.tracker.writer.PdfWriter;

public class App {
  public static void main(String[] args) {
    final List<Artist> artists = FolderReader.getInstance().extractMetaData(new File("/home/harry/Workspaces/FolderTest/"));
    artists.sort(ByAlbumCount.getInstance());
    CsvWriter.getInstance().write(artists, new File("/home/harry/Workspaces/FolderTest/test.csv"));
    PdfWriter.getInstance().write(artists, new File("/home/harry/Workspaces/FolderTest/test.pdf"));    
  }
}
